export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
export const ADD_TOPPERS = 'ADD_TOPPERS';
export const TOPPERS_LOADING = 'TOPPERS_LOADING';
export const TOPPERS_FAILED = 'TOPPERS_FAILED';
export const ADD_PLACEMENTS = 'ADD_PLACEMENTS';
export const PLACEMENTS_LOADING = 'PLACEMENTS_LOADING';
export const PLACEMENTS_FAILED = 'PLACEMENTS_FAILED';