export const ADD_ANNOUNCEMENT = 'ADD_ANNOUNCEMENT';
export const ANNOUNCEMENT_LOADING = 'ANNOUNCEMENT_LOADING';
export const ANNOUNCEMENT_FAILED = 'ANNOUNCEMENT_FAILED';
export const ADD_ANNOUNCEMENTS = 'ADD_ANNOUNCEMENTS'

export const ADD_POSTS = 'ADD_POSTS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAILED = 'POSTS_FAILED';

export const ADD_TOPPERS = 'ADD_TOPPERS';
export const TOPPERS_LOADING = 'TOPPERS_LOADING';
export const TOPPERS_FAILED = 'TOPPERS_FAILED';

export const ADD_PLACEMENTS = 'ADD_PLACEMENTS';
export const PLACEMENTS_LOADING = 'PLACEMENTS_LOADING';
export const PLACEMENTS_FAILED = 'PLACEMENTS_FAILED';